// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd94S2e6zbRXOPJ5c0nfGLzGTE4-8lWnU',
    appId: '1:744293814908:web:64046afcd3741dc9f4eff9',
    messagingSenderId: '744293814908',
    projectId: 'myappmobile-8a3c1',
    authDomain: 'myappmobile-8a3c1.firebaseapp.com',
    storageBucket: 'myappmobile-8a3c1.firebasestorage.app',
    measurementId: 'G-0P5ZJBCG8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3uy8Eq_LuUVRBGzSiDzkzaU-Sd2IV3HI',
    appId: '1:744293814908:android:9111fcbe1b2738fff4eff9',
    messagingSenderId: '744293814908',
    projectId: 'myappmobile-8a3c1',
    storageBucket: 'myappmobile-8a3c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdugITT1QcVGxgru0Va40kkiuthKLIYL0',
    appId: '1:744293814908:ios:e0434559742ac1dff4eff9',
    messagingSenderId: '744293814908',
    projectId: 'myappmobile-8a3c1',
    storageBucket: 'myappmobile-8a3c1.firebasestorage.app',
    iosClientId: '744293814908-2hi6uash6eoo8n2t2kqr9em1ceit60s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdugITT1QcVGxgru0Va40kkiuthKLIYL0',
    appId: '1:744293814908:ios:e0434559742ac1dff4eff9',
    messagingSenderId: '744293814908',
    projectId: 'myappmobile-8a3c1',
    storageBucket: 'myappmobile-8a3c1.firebasestorage.app',
    iosClientId: '744293814908-2hi6uash6eoo8n2t2kqr9em1ceit60s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5oRNsCerIUiI7eTMcTHXFqnb2WO4LMU',
    appId: '1:744293814908:web:20ab0fa78ebfac89f4eff9',
    messagingSenderId: '744293814908',
    projectId: 'myappmobile-8a3c1',
    authDomain: 'myappmobile-8a3c1.firebaseapp.com',
    storageBucket: 'myappmobile-8a3c1.firebasestorage.app',
    measurementId: 'G-4MRYCRGSRX',
  );
}
